import React from "react";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";
const locales = ["en", "hi", "bn", "gu", "kn", "ml", "mr", "or", "ta", "te", "ur"];

export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      <title>BandhuConnect+ — Trusted companion for Mahakumbh</title>
      <meta name="description" content="BandhuConnect+ connects pilgrims with verified volunteers, enabling faster help, safer navigation, and community support at Mahakumbh. (Features rolling out.)" />

      {/* Open Graph */}
      <meta property="og:locale" content="en_US" />
      <meta property="og:type" content="website" />
      <meta property="og:title" content="BandhuConnect+ — Trusted companion for Mahakumbh" />
      <meta property="og:description" content="Connect with volunteers, request help, and navigate large events with confidence. BandhuConnect+ is building tools to keep pilgrims safe and connected." />
      <meta property="og:url" content={siteUrl} />
      <meta property="og:site_name" content="BandhuConnect+" />
  {/* Prefer optimized AVIF hero image generated by the build tools */}
  <meta property="og:image" content={`${siteUrl}/assets/images/optimized/hero-1366.avif`} />
  {/* Preload hero image (LCP) to help the browser discover the resource earlier */}
  <link rel="preload" as="image" href="/assets/images/optimized/hero-1366.avif" />

  {/* Preconnect to Google font domains to speed up font requests */}
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

      {/* Twitter */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@BandhuConnect" />
      <meta name="twitter:title" content="BandhuConnect+ — Trusted companion for Mahakumbh" />
      <meta name="twitter:description" content="Connect with volunteers, request help, and navigate large events with confidence." />
  <meta name="twitter:image" content={`${siteUrl}/assets/images/optimized/hero-1366.avif`} />

      {/* Canonical */}
      <link rel="canonical" href={siteUrl} />

      {/* Hreflang for supported locales */}
      {locales.map((lng) => (
        <link key={lng} rel="alternate" hrefLang={lng} href={`${siteUrl}/${lng}`} />
      ))}

      {/* Basic JSON-LD Organization + WebSite */}
      <script type="application/ld+json">
        {JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebSite",
          name: "BandhuConnect+",
          url: siteUrl,
          potentialAction: {
            "@type": "SearchAction",
            target: `${siteUrl}/?s={search_term_string}`,
            "query-input": "required name=search_term_string",
          },
        })}
      </script>
    </>
  );
}
